version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: car-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: car_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcd1234

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
